name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          additionalArguments: '/overrideconfig mode="Mainline"'
            # Build and push the image
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: docker-build
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/jjournet/echo-app/echo-app:${{ steps.gitversion.outputs.fullSemVer }}
      - name: Update Image version in value file
        run: |
          echo "Updating image version in values.yaml"
          sed -i "s/tag: .*/tag: \"${{ steps.gitversion.outputs.fullSemVer }}\"/" helm/echo-chart/values.yaml
      - uses: azure/setup-helm@v4.2.0
        with:
          version: 'latest'
        id: install
      - name: Helm Install
        run: |
          echo ${{ github.token }} | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          helm package ./helm/echo-chart --app-version ${{ steps.gitversion.outputs.fullSemVer }} --version ${{ steps.gitversion.outputs.fullSemVer }}
          helm push ./echo-chart-${{ steps.gitversion.outputs.fullSemVer }}.tgz oci://ghcr.io/jjournet/echo-app

          
